dist: trusty
sudo: required

# Use ruby environment
language: ruby
rvm:
  - 2.4.2

install:
  - bundle install
  - yarn global add raml-cop

script:
  - rubocop
  - ./scripts/lint-raml-cop.sh
  - COVERAGE=true rake spec
